# Generated by Django 6.0.3 on 2026-03-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_product_and_more'),
        ('products', '0003_color_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'variant')},
        ),
    ]
