# Generated by Django 6.0.3 on 2026-03-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_cat_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_image',
            new_name='category_image',
        ),
    ]
