# Generated by Django 6.0.3 on 2026-03-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_discount_price_product_old_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_image',
            new_name='cat_image',
        ),
    ]
